import { paperlogy } from "../../public/fonts/local_fonts";
import "../css/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={paperlogy.className}>{children}</body>
    </html>
  );
}
